server:
  port: 8080

spring:
  application:
    name: mtracker

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MT_MYSQL_URL}
    username: ${MT_MYSQL_USERNAME}
    password: ${MT_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MT_MAIL_USERNAME}
    password: ${MT_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /api-docs

logging:
  level:
    org:
      springframework: INFO

security:
  jwt:
    secret-key: ${MT_JWT_SECRET_KEY}
    access-token-expiration: ${MT_JWT_ACCESS_EXPIRATION:900000} # 15 min in milliseconds
    refresh-token-expiration: ${MT_JWT_REFRESH_EXPIRATION:86400} # 24 hours in seconds

aws:
  region: ${MT_AWS_REGION:}
  access-key-id: ${MT_AWS_ACCESS_KEY_ID}
  secret-access-key: ${MT_AWS_SECRET_KEY}
  s3:
    bucket-name: ${MT_AWS_S3_BUCKET_NAME}

app:
  frontend-url: ${MT_FRONTEND_URL:https://project-finance-sigma.vercel.app}
